#define _GNU_SOURCE
/*
 * Generated by u2c — U -> C transpiler.
 * Do not edit by hand; regenerate from the .u source instead.
 *
 * See runtime/u_runtime.h for what's real (refcounting, monomorphized
 * lists) vs stubbed (fibers/+A, maps/sets, generators/+W) in this
 * prototype's runtime.
 */
#include "u_runtime.h"
#include <math.h>


typedef struct Field Field;
typedef Field* Field_;
typedef struct Row Row;
typedef Row* Row_;
typedef struct Type Type;
typedef Type* Type_;
U_LIST_DECLARE(char_ptr)
U_LIST_DECLARE(Type_)
U_LIST_DECLARE(Field_)
U_LIST_DECLARE(uint8_t)
U_LIST_DECLARE(Row_)

typedef struct Error Error;
typedef struct Database Database;
typedef struct Database_Connection Database_Connection;
typedef struct Database_Range Database_Range;
typedef struct Database_Row Database_Row;
typedef struct Database_Query Database_Query;
typedef struct Database_Relation Database_Relation;
typedef struct Database_Expression Database_Expression;
typedef struct Row Row;
typedef struct HTTP HTTP;
typedef struct Request Request;
typedef struct Response Response;
typedef struct CookieJar CookieJar;
typedef struct Type Type;
typedef struct Field Field;
typedef struct Method Method;
typedef struct Diagnostic Diagnostic;
typedef struct Position Position;


struct Error {
    URcHeader header;
    char* msg;
}
;

struct Database {
    URcHeader header;
}
;

struct Database_Connection {
    URcHeader header;
    char* engine;
    char* host;
    char* database;
    char* user;
    char* password;
}
;

struct Database_Range {
    URcHeader header;
    char* min;
    char* max;
    bool includeMin;
    bool includeMax;
    bool prefix;
}
;

struct Database_Row {
    URcHeader header;
    char* store;
    char* key;
}
;

struct Database_Query {
    URcHeader header;
    char* store;
}
;

struct Database_Relation {
    URcHeader header;
    char* table;
    char* foreignTable;
    char* joinType;
}
;

struct Database_Expression {
    URcHeader header;
    char* sql;
}
;

struct Row {
    URcHeader header;
}
;

struct HTTP {
    URcHeader header;
}
;

struct Request {
    URcHeader header;
    char* method;
    char* url;
}
;

struct Response {
    URcHeader header;
    int32_t status;
}
;

struct CookieJar {
    URcHeader header;
}
;

struct Type {
    URcHeader header;
    char* name;
    char* kind;
}
;

struct Field {
    URcHeader header;
    char* name;
    int32_t index;
}
;

struct Method {
    URcHeader header;
    char* name;
}
;

struct Diagnostic {
    URcHeader header;
    char* severity;
    char* message;
}
;

struct Position {
    URcHeader header;
    char* tag;
    char* attr;
    int32_t index;
}
;

static inline Error* Error__new(char* msg);
__attribute__((unused)) static Error* Error__copy(Error* self, int32_t depth);
__attribute__((unused)) static inline Error* Error__promote(Error self_value);
static inline Database* Database__new(void);
__attribute__((unused)) static Database* Database__copy(Database* self, int32_t depth);
__attribute__((unused)) static inline Database* Database__promote(Database self_value);
static inline Database_Connection* Database_Connection__new(char* engine, char* host, char* database, char* user, char* password);
__attribute__((unused)) static Database_Connection* Database_Connection__copy(Database_Connection* self, int32_t depth);
__attribute__((unused)) static inline Database_Connection* Database_Connection__promote(Database_Connection self_value);
static inline Database_Range* Database_Range__new(char* min, char* max, bool includeMin, bool includeMax, bool prefix);
__attribute__((unused)) static Database_Range* Database_Range__copy(Database_Range* self, int32_t depth);
__attribute__((unused)) static inline Database_Range* Database_Range__promote(Database_Range self_value);
static inline Database_Row* Database_Row__new(char* store, char* key);
__attribute__((unused)) static Database_Row* Database_Row__copy(Database_Row* self, int32_t depth);
__attribute__((unused)) static inline Database_Row* Database_Row__promote(Database_Row self_value);
static inline Database_Query* Database_Query__new(char* store);
__attribute__((unused)) static Database_Query* Database_Query__copy(Database_Query* self, int32_t depth);
__attribute__((unused)) static inline Database_Query* Database_Query__promote(Database_Query self_value);
static inline Database_Relation* Database_Relation__new(char* table, char* foreignTable, char* joinType);
__attribute__((unused)) static Database_Relation* Database_Relation__copy(Database_Relation* self, int32_t depth);
__attribute__((unused)) static inline Database_Relation* Database_Relation__promote(Database_Relation self_value);
static inline Database_Expression* Database_Expression__new(char* sql);
__attribute__((unused)) static Database_Expression* Database_Expression__copy(Database_Expression* self, int32_t depth);
__attribute__((unused)) static inline Database_Expression* Database_Expression__promote(Database_Expression self_value);
static inline Row* Row__new(void);
__attribute__((unused)) static Row* Row__copy(Row* self, int32_t depth);
__attribute__((unused)) static inline Row* Row__promote(Row self_value);
static inline HTTP* HTTP__new(void);
__attribute__((unused)) static HTTP* HTTP__copy(HTTP* self, int32_t depth);
__attribute__((unused)) static inline HTTP* HTTP__promote(HTTP self_value);
static inline Request* Request__new(char* method, char* url);
__attribute__((unused)) static Request* Request__copy(Request* self, int32_t depth);
__attribute__((unused)) static inline Request* Request__promote(Request self_value);
static inline Response* Response__new(int32_t status);
__attribute__((unused)) static Response* Response__copy(Response* self, int32_t depth);
__attribute__((unused)) static inline Response* Response__promote(Response self_value);
static inline CookieJar* CookieJar__new(void);
__attribute__((unused)) static CookieJar* CookieJar__copy(CookieJar* self, int32_t depth);
__attribute__((unused)) static inline CookieJar* CookieJar__promote(CookieJar self_value);
static inline Type* Type__new(char* name, char* kind);
__attribute__((unused)) static Type* Type__copy(Type* self, int32_t depth);
__attribute__((unused)) static inline Type* Type__promote(Type self_value);
static inline Field* Field__new(char* name, int32_t index);
__attribute__((unused)) static Field* Field__copy(Field* self, int32_t depth);
__attribute__((unused)) static inline Field* Field__promote(Field self_value);
static inline Method* Method__new(char* name);
__attribute__((unused)) static Method* Method__copy(Method* self, int32_t depth);
__attribute__((unused)) static inline Method* Method__promote(Method self_value);
static inline Diagnostic* Diagnostic__new(char* severity, char* message);
__attribute__((unused)) static Diagnostic* Diagnostic__copy(Diagnostic* self, int32_t depth);
__attribute__((unused)) static inline Diagnostic* Diagnostic__promote(Diagnostic self_value);
static inline Position* Position__new(char* tag, char* attr, int32_t index);
__attribute__((unused)) static Position* Position__copy(Position* self, int32_t depth);
__attribute__((unused)) static inline Position* Position__promote(Position self_value);


static inline Error* Error__new(char* msg) {
    Error* self = (Error*)u_alloc(sizeof(Error));
    self->header.type_id = 10;
    self->msg = msg;
    return self;
}

static inline Database* Database__new(void) {
    Database* self = (Database*)u_alloc(sizeof(Database));
    self->header.type_id = 2;
    return self;
}

static inline Database_Connection* Database_Connection__new(char* engine, char* host, char* database, char* user, char* password) {
    Database_Connection* self = (Database_Connection*)u_alloc(sizeof(Database_Connection));
    self->header.type_id = 3;
    self->engine = engine;
    self->host = host;
    self->database = database;
    self->user = user;
    self->password = password;
    return self;
}

static inline Database_Range* Database_Range__new(char* min, char* max, bool includeMin, bool includeMax, bool prefix) {
    Database_Range* self = (Database_Range*)u_alloc(sizeof(Database_Range));
    self->header.type_id = 6;
    self->min = min;
    self->max = max;
    self->includeMin = includeMin;
    self->includeMax = includeMax;
    self->prefix = prefix;
    return self;
}

static inline Database_Row* Database_Row__new(char* store, char* key) {
    Database_Row* self = (Database_Row*)u_alloc(sizeof(Database_Row));
    self->header.type_id = 8;
    self->store = store;
    self->key = key;
    return self;
}

static inline Database_Query* Database_Query__new(char* store) {
    Database_Query* self = (Database_Query*)u_alloc(sizeof(Database_Query));
    self->header.type_id = 5;
    self->store = store;
    return self;
}

static inline Database_Relation* Database_Relation__new(char* table, char* foreignTable, char* joinType) {
    Database_Relation* self = (Database_Relation*)u_alloc(sizeof(Database_Relation));
    self->header.type_id = 7;
    self->table = table;
    self->foreignTable = foreignTable;
    self->joinType = joinType;
    return self;
}

static inline Database_Expression* Database_Expression__new(char* sql) {
    Database_Expression* self = (Database_Expression*)u_alloc(sizeof(Database_Expression));
    self->header.type_id = 4;
    self->sql = sql;
    return self;
}

static inline Row* Row__new(void) {
    Row* self = (Row*)u_alloc(sizeof(Row));
    self->header.type_id = 17;
    return self;
}

static inline HTTP* HTTP__new(void) {
    HTTP* self = (HTTP*)u_alloc(sizeof(HTTP));
    self->header.type_id = 12;
    return self;
}

static inline Request* Request__new(char* method, char* url) {
    Request* self = (Request*)u_alloc(sizeof(Request));
    self->header.type_id = 15;
    self->method = method;
    self->url = url;
    return self;
}

static inline Response* Response__new(int32_t status) {
    Response* self = (Response*)u_alloc(sizeof(Response));
    self->header.type_id = 16;
    self->status = status;
    return self;
}

static inline CookieJar* CookieJar__new(void) {
    CookieJar* self = (CookieJar*)u_alloc(sizeof(CookieJar));
    self->header.type_id = 1;
    return self;
}

static inline Type* Type__new(char* name, char* kind) {
    Type* self = (Type*)u_alloc(sizeof(Type));
    self->header.type_id = 18;
    self->name = name;
    self->kind = kind;
    return self;
}

static inline Field* Field__new(char* name, int32_t index) {
    Field* self = (Field*)u_alloc(sizeof(Field));
    self->header.type_id = 11;
    self->name = name;
    self->index = index;
    return self;
}

static inline Method* Method__new(char* name) {
    Method* self = (Method*)u_alloc(sizeof(Method));
    self->header.type_id = 13;
    self->name = name;
    return self;
}

static inline Diagnostic* Diagnostic__new(char* severity, char* message) {
    Diagnostic* self = (Diagnostic*)u_alloc(sizeof(Diagnostic));
    self->header.type_id = 9;
    self->severity = severity;
    self->message = message;
    return self;
}

static inline Position* Position__new(char* tag, char* attr, int32_t index) {
    Position* self = (Position*)u_alloc(sizeof(Position));
    self->header.type_id = 14;
    self->tag = tag;
    self->attr = attr;
    self->index = index;
    return self;
}

__attribute__((unused)) static Error* Error__copy(Error* self, int32_t depth) {
    Error* result = (Error*)u_alloc(sizeof(Error));
    result->header.type_id = 10;
    result->msg = self->msg;
    return result;
}

__attribute__((unused)) static UTree* u_Error____pack__(Error* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "msg", u_tree_str(self->msg));
    return t;
}
__attribute__((unused)) static Error* u_Error____unpack__(UTree* t) {
    Error* self = (Error*)u_alloc(sizeof(Error));
    self->header.type_id = 10;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "msg");
    if ((v && (v->kind == U_TREE_STR))) self->msg = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Error* Error__promote(Error self_value) {
    Error* result = (Error*)u_alloc(sizeof(Error));
    *result = self_value;
    result->header.type_id = 10;
    return result;
}

__attribute__((unused)) static Database* Database__copy(Database* self, int32_t depth) {
    Database* result = (Database*)u_alloc(sizeof(Database));
    result->header.type_id = 2;
    return result;
}

__attribute__((unused)) static UTree* u_Database____pack__(Database* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    return t;
}
__attribute__((unused)) static Database* u_Database____unpack__(UTree* t) {
    Database* self = (Database*)u_alloc(sizeof(Database));
    self->header.type_id = 2;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    return self;
}
__attribute__((unused)) static inline Database* Database__promote(Database self_value) {
    Database* result = (Database*)u_alloc(sizeof(Database));
    *result = self_value;
    result->header.type_id = 2;
    return result;
}

__attribute__((unused)) static Database_Connection* Database_Connection__copy(Database_Connection* self, int32_t depth) {
    Database_Connection* result = (Database_Connection*)u_alloc(sizeof(Database_Connection));
    result->header.type_id = 3;
    result->engine = self->engine;
    result->host = self->host;
    result->database = self->database;
    result->user = self->user;
    result->password = self->password;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Connection____pack__(Database_Connection* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "engine", u_tree_str(self->engine));
    u_tree_set(t, "host", u_tree_str(self->host));
    u_tree_set(t, "database", u_tree_str(self->database));
    u_tree_set(t, "user", u_tree_str(self->user));
    u_tree_set(t, "password", u_tree_str(self->password));
    return t;
}
__attribute__((unused)) static Database_Connection* u_Database_Connection____unpack__(UTree* t) {
    Database_Connection* self = (Database_Connection*)u_alloc(sizeof(Database_Connection));
    self->header.type_id = 3;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "engine");
    if ((v && (v->kind == U_TREE_STR))) self->engine = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "host");
    if ((v && (v->kind == U_TREE_STR))) self->host = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "database");
    if ((v && (v->kind == U_TREE_STR))) self->database = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "user");
    if ((v && (v->kind == U_TREE_STR))) self->user = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "password");
    if ((v && (v->kind == U_TREE_STR))) self->password = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Connection* Database_Connection__promote(Database_Connection self_value) {
    Database_Connection* result = (Database_Connection*)u_alloc(sizeof(Database_Connection));
    *result = self_value;
    result->header.type_id = 3;
    return result;
}

__attribute__((unused)) static Database_Range* Database_Range__copy(Database_Range* self, int32_t depth) {
    Database_Range* result = (Database_Range*)u_alloc(sizeof(Database_Range));
    result->header.type_id = 6;
    result->min = self->min;
    result->max = self->max;
    result->includeMin = self->includeMin;
    result->includeMax = self->includeMax;
    result->prefix = self->prefix;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Range____pack__(Database_Range* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "min", u_tree_str(self->min));
    u_tree_set(t, "max", u_tree_str(self->max));
    u_tree_set(t, "includeMin", u_tree_bool(self->includeMin));
    u_tree_set(t, "includeMax", u_tree_bool(self->includeMax));
    u_tree_set(t, "prefix", u_tree_bool(self->prefix));
    return t;
}
__attribute__((unused)) static Database_Range* u_Database_Range____unpack__(UTree* t) {
    Database_Range* self = (Database_Range*)u_alloc(sizeof(Database_Range));
    self->header.type_id = 6;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "min");
    if ((v && (v->kind == U_TREE_STR))) self->min = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "max");
    if ((v && (v->kind == U_TREE_STR))) self->max = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "includeMin");
    if ((v && (v->kind == U_TREE_BOOL))) self->includeMin = v->as.b;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "includeMax");
    if ((v && (v->kind == U_TREE_BOOL))) self->includeMax = v->as.b;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "prefix");
    if ((v && (v->kind == U_TREE_BOOL))) self->prefix = v->as.b;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Range* Database_Range__promote(Database_Range self_value) {
    Database_Range* result = (Database_Range*)u_alloc(sizeof(Database_Range));
    *result = self_value;
    result->header.type_id = 6;
    return result;
}

__attribute__((unused)) static Database_Row* Database_Row__copy(Database_Row* self, int32_t depth) {
    Database_Row* result = (Database_Row*)u_alloc(sizeof(Database_Row));
    result->header.type_id = 8;
    result->store = self->store;
    result->key = self->key;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Row____pack__(Database_Row* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "store", u_tree_str(self->store));
    u_tree_set(t, "key", u_tree_str(self->key));
    return t;
}
__attribute__((unused)) static Database_Row* u_Database_Row____unpack__(UTree* t) {
    Database_Row* self = (Database_Row*)u_alloc(sizeof(Database_Row));
    self->header.type_id = 8;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "store");
    if ((v && (v->kind == U_TREE_STR))) self->store = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "key");
    if ((v && (v->kind == U_TREE_STR))) self->key = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Row* Database_Row__promote(Database_Row self_value) {
    Database_Row* result = (Database_Row*)u_alloc(sizeof(Database_Row));
    *result = self_value;
    result->header.type_id = 8;
    return result;
}

__attribute__((unused)) static Database_Query* Database_Query__copy(Database_Query* self, int32_t depth) {
    Database_Query* result = (Database_Query*)u_alloc(sizeof(Database_Query));
    result->header.type_id = 5;
    result->store = self->store;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Query____pack__(Database_Query* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "store", u_tree_str(self->store));
    return t;
}
__attribute__((unused)) static Database_Query* u_Database_Query____unpack__(UTree* t) {
    Database_Query* self = (Database_Query*)u_alloc(sizeof(Database_Query));
    self->header.type_id = 5;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "store");
    if ((v && (v->kind == U_TREE_STR))) self->store = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Query* Database_Query__promote(Database_Query self_value) {
    Database_Query* result = (Database_Query*)u_alloc(sizeof(Database_Query));
    *result = self_value;
    result->header.type_id = 5;
    return result;
}

__attribute__((unused)) static Database_Relation* Database_Relation__copy(Database_Relation* self, int32_t depth) {
    Database_Relation* result = (Database_Relation*)u_alloc(sizeof(Database_Relation));
    result->header.type_id = 7;
    result->table = self->table;
    result->foreignTable = self->foreignTable;
    result->joinType = self->joinType;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Relation____pack__(Database_Relation* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "table", u_tree_str(self->table));
    u_tree_set(t, "foreignTable", u_tree_str(self->foreignTable));
    u_tree_set(t, "joinType", u_tree_str(self->joinType));
    return t;
}
__attribute__((unused)) static Database_Relation* u_Database_Relation____unpack__(UTree* t) {
    Database_Relation* self = (Database_Relation*)u_alloc(sizeof(Database_Relation));
    self->header.type_id = 7;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "table");
    if ((v && (v->kind == U_TREE_STR))) self->table = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "foreignTable");
    if ((v && (v->kind == U_TREE_STR))) self->foreignTable = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "joinType");
    if ((v && (v->kind == U_TREE_STR))) self->joinType = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Relation* Database_Relation__promote(Database_Relation self_value) {
    Database_Relation* result = (Database_Relation*)u_alloc(sizeof(Database_Relation));
    *result = self_value;
    result->header.type_id = 7;
    return result;
}

__attribute__((unused)) static Database_Expression* Database_Expression__copy(Database_Expression* self, int32_t depth) {
    Database_Expression* result = (Database_Expression*)u_alloc(sizeof(Database_Expression));
    result->header.type_id = 4;
    result->sql = self->sql;
    return result;
}

__attribute__((unused)) static UTree* u_Database_Expression____pack__(Database_Expression* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "sql", u_tree_str(self->sql));
    return t;
}
__attribute__((unused)) static Database_Expression* u_Database_Expression____unpack__(UTree* t) {
    Database_Expression* self = (Database_Expression*)u_alloc(sizeof(Database_Expression));
    self->header.type_id = 4;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "sql");
    if ((v && (v->kind == U_TREE_STR))) self->sql = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Database_Expression* Database_Expression__promote(Database_Expression self_value) {
    Database_Expression* result = (Database_Expression*)u_alloc(sizeof(Database_Expression));
    *result = self_value;
    result->header.type_id = 4;
    return result;
}

__attribute__((unused)) static Row* Row__copy(Row* self, int32_t depth) {
    Row* result = (Row*)u_alloc(sizeof(Row));
    result->header.type_id = 17;
    return result;
}

__attribute__((unused)) static UTree* u_Row____pack__(Row* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    return t;
}
__attribute__((unused)) static Row* u_Row____unpack__(UTree* t) {
    Row* self = (Row*)u_alloc(sizeof(Row));
    self->header.type_id = 17;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    return self;
}
__attribute__((unused)) static inline Row* Row__promote(Row self_value) {
    Row* result = (Row*)u_alloc(sizeof(Row));
    *result = self_value;
    result->header.type_id = 17;
    return result;
}

__attribute__((unused)) static HTTP* HTTP__copy(HTTP* self, int32_t depth) {
    HTTP* result = (HTTP*)u_alloc(sizeof(HTTP));
    result->header.type_id = 12;
    return result;
}

__attribute__((unused)) static UTree* u_HTTP____pack__(HTTP* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    return t;
}
__attribute__((unused)) static HTTP* u_HTTP____unpack__(UTree* t) {
    HTTP* self = (HTTP*)u_alloc(sizeof(HTTP));
    self->header.type_id = 12;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    return self;
}
__attribute__((unused)) static inline HTTP* HTTP__promote(HTTP self_value) {
    HTTP* result = (HTTP*)u_alloc(sizeof(HTTP));
    *result = self_value;
    result->header.type_id = 12;
    return result;
}

__attribute__((unused)) static Request* Request__copy(Request* self, int32_t depth) {
    Request* result = (Request*)u_alloc(sizeof(Request));
    result->header.type_id = 15;
    result->method = self->method;
    result->url = self->url;
    return result;
}

__attribute__((unused)) static UTree* u_Request____pack__(Request* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "method", u_tree_str(self->method));
    u_tree_set(t, "url", u_tree_str(self->url));
    return t;
}
__attribute__((unused)) static Request* u_Request____unpack__(UTree* t) {
    Request* self = (Request*)u_alloc(sizeof(Request));
    self->header.type_id = 15;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "method");
    if ((v && (v->kind == U_TREE_STR))) self->method = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "url");
    if ((v && (v->kind == U_TREE_STR))) self->url = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Request* Request__promote(Request self_value) {
    Request* result = (Request*)u_alloc(sizeof(Request));
    *result = self_value;
    result->header.type_id = 15;
    return result;
}

__attribute__((unused)) static Response* Response__copy(Response* self, int32_t depth) {
    Response* result = (Response*)u_alloc(sizeof(Response));
    result->header.type_id = 16;
    result->status = self->status;
    return result;
}

__attribute__((unused)) static UTree* u_Response____pack__(Response* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "status", u_tree_int((int64_t)self->status));
    return t;
}
__attribute__((unused)) static Response* u_Response____unpack__(UTree* t) {
    Response* self = (Response*)u_alloc(sizeof(Response));
    self->header.type_id = 16;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "status");
    if ((v && (v->kind == U_TREE_INT))) self->status = (int32_t)(v->as.i);
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Response* Response__promote(Response self_value) {
    Response* result = (Response*)u_alloc(sizeof(Response));
    *result = self_value;
    result->header.type_id = 16;
    return result;
}

__attribute__((unused)) static CookieJar* CookieJar__copy(CookieJar* self, int32_t depth) {
    CookieJar* result = (CookieJar*)u_alloc(sizeof(CookieJar));
    result->header.type_id = 1;
    return result;
}

__attribute__((unused)) static UTree* u_CookieJar____pack__(CookieJar* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    return t;
}
__attribute__((unused)) static CookieJar* u_CookieJar____unpack__(UTree* t) {
    CookieJar* self = (CookieJar*)u_alloc(sizeof(CookieJar));
    self->header.type_id = 1;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    return self;
}
__attribute__((unused)) static inline CookieJar* CookieJar__promote(CookieJar self_value) {
    CookieJar* result = (CookieJar*)u_alloc(sizeof(CookieJar));
    *result = self_value;
    result->header.type_id = 1;
    return result;
}

__attribute__((unused)) static Type* Type__copy(Type* self, int32_t depth) {
    Type* result = (Type*)u_alloc(sizeof(Type));
    result->header.type_id = 18;
    result->name = self->name;
    result->kind = self->kind;
    return result;
}

__attribute__((unused)) static UTree* u_Type____pack__(Type* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "name", u_tree_str(self->name));
    u_tree_set(t, "kind", u_tree_str(self->kind));
    return t;
}
__attribute__((unused)) static Type* u_Type____unpack__(UTree* t) {
    Type* self = (Type*)u_alloc(sizeof(Type));
    self->header.type_id = 18;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "name");
    if ((v && (v->kind == U_TREE_STR))) self->name = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "kind");
    if ((v && (v->kind == U_TREE_STR))) self->kind = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Type* Type__promote(Type self_value) {
    Type* result = (Type*)u_alloc(sizeof(Type));
    *result = self_value;
    result->header.type_id = 18;
    return result;
}

__attribute__((unused)) static Field* Field__copy(Field* self, int32_t depth) {
    Field* result = (Field*)u_alloc(sizeof(Field));
    result->header.type_id = 11;
    result->name = self->name;
    result->index = self->index;
    return result;
}

__attribute__((unused)) static UTree* u_Field____pack__(Field* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "name", u_tree_str(self->name));
    u_tree_set(t, "index", u_tree_int((int64_t)self->index));
    return t;
}
__attribute__((unused)) static Field* u_Field____unpack__(UTree* t) {
    Field* self = (Field*)u_alloc(sizeof(Field));
    self->header.type_id = 11;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "name");
    if ((v && (v->kind == U_TREE_STR))) self->name = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "index");
    if ((v && (v->kind == U_TREE_INT))) self->index = (int32_t)(v->as.i);
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Field* Field__promote(Field self_value) {
    Field* result = (Field*)u_alloc(sizeof(Field));
    *result = self_value;
    result->header.type_id = 11;
    return result;
}

__attribute__((unused)) static Method* Method__copy(Method* self, int32_t depth) {
    Method* result = (Method*)u_alloc(sizeof(Method));
    result->header.type_id = 13;
    result->name = self->name;
    return result;
}

__attribute__((unused)) static UTree* u_Method____pack__(Method* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "name", u_tree_str(self->name));
    return t;
}
__attribute__((unused)) static Method* u_Method____unpack__(UTree* t) {
    Method* self = (Method*)u_alloc(sizeof(Method));
    self->header.type_id = 13;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "name");
    if ((v && (v->kind == U_TREE_STR))) self->name = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Method* Method__promote(Method self_value) {
    Method* result = (Method*)u_alloc(sizeof(Method));
    *result = self_value;
    result->header.type_id = 13;
    return result;
}

__attribute__((unused)) static Diagnostic* Diagnostic__copy(Diagnostic* self, int32_t depth) {
    Diagnostic* result = (Diagnostic*)u_alloc(sizeof(Diagnostic));
    result->header.type_id = 9;
    result->severity = self->severity;
    result->message = self->message;
    return result;
}

__attribute__((unused)) static UTree* u_Diagnostic____pack__(Diagnostic* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "severity", u_tree_str(self->severity));
    u_tree_set(t, "message", u_tree_str(self->message));
    return t;
}
__attribute__((unused)) static Diagnostic* u_Diagnostic____unpack__(UTree* t) {
    Diagnostic* self = (Diagnostic*)u_alloc(sizeof(Diagnostic));
    self->header.type_id = 9;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "severity");
    if ((v && (v->kind == U_TREE_STR))) self->severity = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "message");
    if ((v && (v->kind == U_TREE_STR))) self->message = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Diagnostic* Diagnostic__promote(Diagnostic self_value) {
    Diagnostic* result = (Diagnostic*)u_alloc(sizeof(Diagnostic));
    *result = self_value;
    result->header.type_id = 9;
    return result;
}

__attribute__((unused)) static Position* Position__copy(Position* self, int32_t depth) {
    Position* result = (Position*)u_alloc(sizeof(Position));
    result->header.type_id = 14;
    result->tag = self->tag;
    result->attr = self->attr;
    result->index = self->index;
    return result;
}

__attribute__((unused)) static UTree* u_Position____pack__(Position* self) {
    UTree* t = u_tree_new(U_TREE_NODE);
    if (!self) return t;
    u_tree_set(t, "tag", u_tree_str(self->tag));
    u_tree_set(t, "attr", u_tree_str(self->attr));
    u_tree_set(t, "index", u_tree_int((int64_t)self->index));
    return t;
}
__attribute__((unused)) static Position* u_Position____unpack__(UTree* t) {
    Position* self = (Position*)u_alloc(sizeof(Position));
    self->header.type_id = 14;
    if (!t || t->kind != U_TREE_NODE) return self;
    UTree* v = NULL; (void)v;
    v = u_tree_get(t, "tag");
    if ((v && (v->kind == U_TREE_STR))) self->tag = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "attr");
    if ((v && (v->kind == U_TREE_STR))) self->attr = v->as.s;
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    v = u_tree_get(t, "index");
    if ((v && (v->kind == U_TREE_INT))) self->index = (int32_t)(v->as.i);
    else if (v) { u_throw(U_ERR_USER, "UnpackFailed"); }
    return self;
}
__attribute__((unused)) static inline Position* Position__promote(Position self_value) {
    Position* result = (Position*)u_alloc(sizeof(Position));
    *result = self_value;
    result->header.type_id = 14;
    return result;
}

static char* u_handle_path__S(char* path) {
    if ((strcmp(path, "/") == 0)) {
        return "Hello from U!";
    }
    if ((strcmp(path, "/json") == 0)) {
        return "{\"status\":\"ok\",\"server\":\"U WebServer\"}";
    }
    if ((strcmp(path, "/health") == 0)) {
        return "ok";
    }
    return "";
}

static int32_t u_get_status__S(char* path) {
    if ((strcmp(path, "/") == 0)) {
        return 200;
    }
    if ((strcmp(path, "/json") == 0)) {
        return 200;
    }
    if ((strcmp(path, "/health") == 0)) {
        return 200;
    }
    return 404;
}

static char* u_get_content_type__S(char* path) {
    if ((strcmp(path, "/json") == 0)) {
        return "application/json";
    }
    return "text/plain";
}


#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <signal.h>
#include <sys/socket.h>
#include <sys/epoll.h>
#include <netinet/in.h>
#include <netinet/tcp.h>
#include <time.h>
#include <getopt.h>
#include "u_tls.h"
#include "u_sendfile.h"
#include "u_merkle_cache.h"

#define MAX_EVENTS 256
#define MAX_CONNS 8192
#define BUF_SIZE 8192
#define CACHE_SIZE 256

static volatile int running = 1;
void sighandler(int s) { running = 0; }

/* ── Per-connection state ─────────────────────────────── */
typedef struct {
    int fd;
    char buf[BUF_SIZE];
    int buf_len;
    int keep_alive;
    UTlsConn* tls;  /* NULL for plain HTTP */
} Conn;

static Conn conns[MAX_CONNS];
static int epfd;

/* ── Response cache ───────────────────────────────────── */
typedef struct {
    char path[128];
    char response[4096];
    int resp_len;
    time_t expires;
} CacheSlot;

static CacheSlot cache[CACHE_SIZE];
static long cache_hits = 0, cache_misses = 0;

static CacheSlot* cache_lookup(const char* path) {
    unsigned h = 5381;
    for (const char* p = path; *p; p++) h = h * 33 + *p;
    CacheSlot* s = &cache[h % CACHE_SIZE];
    if (s->resp_len > 0 && strcmp(s->path, path) == 0 &&
        (s->expires == 0 || s->expires > time(NULL))) {
        cache_hits++;
        return s;
    }
    return NULL;
}

static void cache_store(const char* path, const char* resp, int rlen, int ttl) {
    unsigned h = 5381;
    for (const char* p = path; *p; p++) h = h * 33 + *p;
    CacheSlot* s = &cache[h % CACHE_SIZE];
    strncpy(s->path, path, 127); s->path[127] = 0;
    if (rlen > 4095) rlen = 4095;
    memcpy(s->response, resp, rlen);
    s->resp_len = rlen;
    s->expires = ttl > 0 ? time(NULL) + ttl : 0;
    cache_misses++;
}

/* ── Date header (cached per second) ──────────────────── */
static char date_hdr[80];
static time_t last_date = 0;
static void update_date(void) {
    time_t now = time(NULL);
    if (now != last_date) {
        struct tm tm; gmtime_r(&now, &tm);
        strftime(date_hdr, sizeof(date_hdr),
                 "Date: %a, %d %b %Y %H:%M:%S GMT", &tm);
        last_date = now;
    }
}

/* ── Stats ────────────────────────────────────────────── */
static long total_requests = 0;
static MerkleCache* merkle = NULL;
static long total_bytes = 0;
static time_t start_time;

/* ── I/O wrappers (plain or TLS) ──────────────────────── */
static int conn_read(Conn* c, void* buf, int len) {
    return c->tls ? u_tls_read(c->tls, buf, len) : read(c->fd, buf, len);
}
static int conn_write(Conn* c, const void* buf, int len) {
    return c->tls ? u_tls_write(c->tls, buf, len) : write(c->fd, buf, len);
}
static void conn_close(Conn* c) {
    if (c->tls) { u_tls_close(c->tls); c->tls = NULL; }
    if (c->fd > 0) { close(c->fd); }
    c->fd = 0; c->buf_len = 0;
}

/* ── Handle one request ──────────────────────────────── */
static void handle_request(Conn* c) {
    char* buf = c->buf; buf[c->buf_len] = 0;
    char path[256] = "/";
    char* sp1 = memchr(buf, ' ', c->buf_len);
    if (sp1) {
        char* sp2 = memchr(sp1+1, ' ', c->buf_len - (sp1+1-buf));
        if (sp2) {
            int plen = sp2 - sp1 - 1;
            if (plen > 0 && plen < 255) { memcpy(path, sp1+1, plen); path[plen] = 0; }
        }
    }
    c->keep_alive = 1;
    if (memmem(buf, c->buf_len, "Connection: close", 17)) c->keep_alive = 0;

    /* Health endpoint with stats */
    if (strcmp(path, "/health") == 0) {
        update_date();
        char body[512];
        int blen = snprintf(body, sizeof(body),
            "{\"status\":\"ok\",\"requests\":%ld,\"cache_hits\":%ld,"
            "\"cache_misses\":%ld,\"uptime\":%ld,"
            "\"merkle_trees\":%d,\"merkle_deps\":%d,\"merkle_invalidations\":%ld}",
            total_requests, cache_hits, cache_misses,
            (long)(time(NULL) - start_time),
            merkle->tree_count, merkle->dep_count, merkle->invalidations);
        char resp[1024];
        int rlen = snprintf(resp, sizeof(resp),
            "HTTP/1.1 200 OK\r\n%s\r\n"
            "Content-Type: application/json\r\n"
            "Content-Length: %d\r\n"
            "Connection: %s\r\nServer: U/1.0\r\n\r\n%s",
            date_hdr, blen, c->keep_alive ? "keep-alive" : "close", body);
        conn_write(c, resp, rlen);
        c->buf_len = 0; total_requests++; total_bytes += rlen;
        return;
    }

    /* Cache check */
    CacheSlot* cached = cache_lookup(path);
    if (cached) {
        conn_write(c, cached->response, cached->resp_len);
        c->buf_len = 0; total_requests++; total_bytes += cached->resp_len;
        return;
    }

    /* Call U handler */
    char* body = u_handle_path__S(path);
    int status = u_get_status__S(path);
    char* ctype = u_get_content_type__S(path);
    int blen = body ? strlen(body) : 0;
    update_date();

    char resp[4096];
    int rlen = snprintf(resp, sizeof(resp),
        "HTTP/1.1 %d %s\r\n%s\r\n"
        "Content-Type: %s\r\nContent-Length: %d\r\n"
        "Connection: %s\r\nServer: U/1.0\r\n\r\n%s",
        status, status == 200 ? "OK" : "Not Found",
        date_hdr, ctype, blen,
        c->keep_alive ? "keep-alive" : "close",
        body ? body : "");

    if (status == 200 && rlen < 4096)
        cache_store(path, resp, rlen, 60);

    conn_write(c, resp, rlen);
    c->buf_len = 0; total_requests++; total_bytes += rlen;
}

/* ── Accept ──────────────────────────────────────────── */
static UTlsCtx* tls_ctx = NULL;

static void do_accept(int listen_fd, int is_tls) {
    while (1) {
        int fd = accept4(listen_fd, NULL, NULL, SOCK_NONBLOCK);
        if (fd < 0) break;
        if (fd >= MAX_CONNS) { close(fd); continue; }
        int one = 1;
        setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, &one, sizeof(one));

        Conn* c = &conns[fd];
        c->fd = fd; c->buf_len = 0; c->keep_alive = 1; c->tls = NULL;

        if (is_tls && tls_ctx) {
            /* Blocking TLS handshake (could be async with more work) */
            int flags = fcntl(fd, F_GETFL); fcntl(fd, F_SETFL, flags & ~O_NONBLOCK);
            c->tls = u_tls_accept(tls_ctx, fd);
            fcntl(fd, F_SETFL, flags);
            if (!c->tls) { close(fd); c->fd = 0; continue; }
        }

        struct epoll_event ev = { .events = EPOLLIN | EPOLLET, .data.fd = fd };
        epoll_ctl(epfd, EPOLL_CTL_ADD, fd, &ev);
    }
}

/* ── Read ────────────────────────────────────────────── */
static void do_read(int fd) {
    Conn* c = &conns[fd];
    while (1) {
        int space = BUF_SIZE - c->buf_len - 1;
        if (space <= 0) { c->buf_len = 0; break; }
        int n = conn_read(c, c->buf + c->buf_len, space);
        if (n <= 0) {
            if (n == 0 || (errno != EAGAIN && errno != EWOULDBLOCK)) {
                epoll_ctl(epfd, EPOLL_CTL_DEL, fd, NULL);
                conn_close(c);
            }
            return;
        }
        c->buf_len += n;

        /* Drain EVERY complete request already in the buffer.
         *
         * A client may pipeline several requests in one write. The old code
         * handled the first and returned; handle_request() sets buf_len = 0,
         * so the rest were discarded unread. And because the socket is
         * EPOLLET, those bytes never produce another readiness edge -- epoll
         * never reports the fd again and the client blocks forever waiting
         * for responses that will never come. Symptom: 1 of 3 responses.
         */
        char* hend;
        while ((hend = memmem(c->buf, c->buf_len, "\r\n\r\n", 4)) != NULL) {
            int consumed = (int)(hend - c->buf) + 4;
            /* Defensive: never trust this arithmetic enough to memmove on it. */
            if (consumed <= 0 || consumed > c->buf_len) { c->buf_len = 0; break; }
            int leftover = c->buf_len - consumed;

            /* Scope handle_request to THIS request only. It scans the whole
             * buffer -- e.g. memmem(buf, buf_len, "Connection: close") -- so
             * with pipelining a later request's "Connection: close" would tear
             * down the connection while an earlier one was still being served.
             */
            char next_byte = c->buf[consumed];  /* handle_request NUL-terminates here */
            c->buf_len = consumed;

            handle_request(c);                  /* resets buf_len to 0 */

            /* handle_request only writes that one NUL and clears the length --
             * it never touches the bytes behind the request. So the pipelined
             * data is still intact and a memmove is enough. No scratch buffer,
             * hence no stack-smash risk from a mis-computed length.
             */
            c->buf[consumed] = next_byte;
            if (leftover > 0) memmove(c->buf, c->buf + consumed, leftover);
            c->buf_len = leftover;

            if (!c->keep_alive) {
                epoll_ctl(epfd, EPOLL_CTL_DEL, fd, NULL);
                conn_close(c);
                return;
            }
            if (leftover == 0) break;
        }
        /* Do NOT return here. Under EPOLLET the fd must be read until EAGAIN,
         * or anything that arrived after the last read stays stuck. The loop
         * exits through the n <= 0 branch above.
         */
    }
}

/* The release and build, given when it is compiled:
 *   gcc -O2 -DUWEB_VERSION="\"$(git describe --tags --abbrev=0)\"" \
 *       -DUWEB_BUILD="\"$(git rev-parse --short HEAD)\"" -o sbin/uwebserver native/uwebserver/uwebserver.c ...
 * so the source never states a version that has gone out of date. */
#ifndef UWEB_VERSION
#define UWEB_VERSION "(version not given at build time)"
#endif
#ifndef UWEB_BUILD
#define UWEB_BUILD "source"
#endif

#include "u_options.h"

enum { OPT_HELP = 1, OPT_VERSION, OPT_ABOUT, OPT_PORT, OPT_TLS_PORT, OPT_CERT, OPT_KEY };

static const UwOpt uw_options[] = {
    { "port",      'p', UWO_VALUE, OPT_PORT,     "PORT", "serve HTTP on PORT (default 8080)" },
    { "tls-port",  0,   UWO_VALUE, OPT_TLS_PORT, "PORT", "serve HTTPS on PORT (default 8443 with --cert)" },
    { "cert",      0,   UWO_VALUE, OPT_CERT,     "FILE", "the certificate (PEM, with its chain) for HTTPS" },
    { "key",       0,   UWO_VALUE, OPT_KEY,      "FILE", "the private key (PEM) of --cert" },
    { "help",      'h', UWO_CLI_ONLY, OPT_HELP,    NULL, "print this help and exit" },
    { "version",   'V', UWO_CLI_ONLY, OPT_VERSION, NULL, "print the version and exit" },
    { "about",     0,   UWO_CLI_ONLY, OPT_ABOUT,   NULL, "print the version with build details and exit" },
    { "copyright", 0,   UWO_CLI_ONLY | UWO_HIDDEN, OPT_ABOUT, NULL, NULL },
    { "",          'v', UWO_CLI_ONLY | UWO_HIDDEN, OPT_VERSION, NULL, NULL },
    { NULL, 0, 0, 0, NULL, NULL }
};

static void uw_print_help(void) {
    printf("Usage: %s [OPTION]...\n"
           "A small web server in C for benchmarks and tests beside Exponential Velocity.\n\n",
           uw_progname);
    for (const UwOpt *o = uw_options; o->name; o++) {
        if (o->flags & UWO_HIDDEN) continue;
        char left[64];
        if (o->shortc) snprintf(left, sizeof left, "-%c, --%s%s%s", o->shortc, o->name, o->argname ? "=" : "", o->argname ? o->argname : "");
        else snprintf(left, sizeof left, "    --%s%s%s", o->name, o->argname ? "=" : "", o->argname ? o->argname : "");
        printf("  %-26s %s\n", left, o->help);
    }
    printf("\nExit status: 0 on success, 1 when the server cannot start, 2 on a usage error.\n\n"
           "Report bugs to: https://github.com/se7enxweb/exponential-velocity/issues\n"
           "Home page: <https://github.com/se7enxweb/exponential-velocity>\n");
}

/* --version, -V, -v, --about, --copyright (and -version, -about, -copyright):
 * what this program is, the way the PHP programs of the server say it
 * (Q_WebServer_About), GNU style. */
static void uw_print_about(void) {
    printf("uwebserver (Exponential Velocity) %s\n"
           "A small web server in C for benchmarks and tests beside Exponential Velocity:\n"
           "HTTP and HTTPS with keep-alive and pipelining.\n\n"
           "  Program:      uwebserver -- a minimal web server, compiled\n"
           "  Version:      %s+%s\n"
           "  Built:        %s %s, %s\n"
           "  Options:      uwebserver --help\n"
           "  Home page:    https://github.com/se7enxweb/exponential-velocity\n\n"
           "Copyright (C) 2026 7x (se7enx.com) -- Exponential Velocity\n"
           "Copyright (C) 2024-2026 Qbix, Inc.\n"
           "License MIT: <https://opensource.org/license/mit>; the full text is in\n"
           "the LICENSE file that comes with the program.\n"
           "This is free software: you are free to change and redistribute it.\n"
           "There is NO WARRANTY, to the extent permitted by law.\n\n"
           "Written by 7x (se7enx.com), on the Qbix Server by Qbix, Inc. and contributors.\n",
           UWEB_VERSION, UWEB_VERSION, UWEB_BUILD, __DATE__, __TIME__,
#ifdef __VERSION__
           "compiler " __VERSION__
#else
           "unknown compiler"
#endif
           );
}

static int uw_port_value(const UwArg *a) {
    long long v;
    if (uw_parse_long(a->value, 1, 65535, &v) != 0)
        uw_usage_error("invalid port '%s' for '%s' (1 to 65535)", a->value, a->spelled);
    return (int)v;
}

int main(int argc, char** argv) {
    UwParsed parsed;
    uw_parse_argv(uw_options, argc, argv, &parsed);   /* exits 2 on any error */

    int port = 8080, tls_port = 0;
    const char *cert = NULL, *key = NULL;

    for (int i = 0; i < parsed.nargs; i++) {
        const UwArg *a = &parsed.args[i];
        switch (a->opt->id) {
        case OPT_HELP:    uw_print_help();  return 0;
        case OPT_VERSION:
        case OPT_ABOUT:   uw_print_about(); return 0;
        default: break;
        }
    }
    /* A bare number was once read as the port: still accepted, with a note. */
    for (int i = 0; i < parsed.nwords; i++) {
        long long v;
        if (uw_parse_long(parsed.words[i], 1, 65535, &v) != 0)
            uw_usage_error("unexpected argument '%s'", parsed.words[i]);
        fprintf(stderr, "%s: a port given as a bare argument is deprecated; use --port=%s\n", uw_progname, parsed.words[i]);
        port = (int)v;
    }
    for (int i = 0; i < parsed.nargs; i++) {
        const UwArg *a = &parsed.args[i];
        switch (a->opt->id) {
        case OPT_PORT:     port = uw_port_value(a); break;
        case OPT_TLS_PORT: tls_port = uw_port_value(a); break;
        case OPT_CERT:     cert = a->value; break;
        case OPT_KEY:      key = a->value; break;
        default: break;
        }
    }
    if ((cert != NULL) != (key != NULL))
        uw_usage_error("%s", cert ? "--cert needs --key" : "--key needs --cert");
    if (tls_port && !cert)
        uw_usage_error("--tls-port needs --cert and --key");

    signal(SIGINT, sighandler);
    signal(SIGTERM, sighandler);
    signal(SIGPIPE, SIG_IGN);

    /* TLS setup */
    if (cert && key) {
        UTlsCertInfo info = u_tls_cert_info(cert);
        tls_ctx = u_tls_ctx_new(cert, key, "1.2");
        if (!tls_ctx) { fprintf(stderr, "TLS init failed: %s\n", u_tls_last_error()); return 1; }
        printf("TLS: %s (expires in %d days, SAN: %s)\n",
               info.subject, info.days_remaining, info.san[0] ? info.san : "none");
        if (tls_port == 0) tls_port = 8443;
    }

    epfd = epoll_create1(0);
    memset(cache, 0, sizeof(cache));
    memset(conns, 0, sizeof(conns));
    start_time = time(NULL);
    merkle = merkle_cache_new();

    /* HTTP listener */
    int sock = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK, 0);
    int opt = 1;
    setsockopt(sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
    setsockopt(sock, SOL_SOCKET, SO_REUSEPORT, &opt, sizeof(opt));
    struct sockaddr_in addr = {0};
    addr.sin_family = AF_INET; addr.sin_addr.s_addr = INADDR_ANY; addr.sin_port = htons(port);
    if (bind(sock, (struct sockaddr*)&addr, sizeof(addr)) < 0) { perror("bind HTTP"); return 1; }
    listen(sock, 4096);
    struct epoll_event ev = { .events = EPOLLIN, .data.fd = sock };
    epoll_ctl(epfd, EPOLL_CTL_ADD, sock, &ev);
    printf("⚡ U WebServer on :%d", port);

    /* HTTPS listener */
    int tls_sock = -1;
    if (tls_ctx && tls_port > 0) {
        tls_sock = socket(AF_INET, SOCK_STREAM | SOCK_NONBLOCK, 0);
        setsockopt(tls_sock, SOL_SOCKET, SO_REUSEADDR, &opt, sizeof(opt));
        struct sockaddr_in taddr = {0};
        taddr.sin_family = AF_INET; taddr.sin_addr.s_addr = INADDR_ANY; taddr.sin_port = htons(tls_port);
        if (bind(tls_sock, (struct sockaddr*)&taddr, sizeof(taddr)) < 0) { perror("bind HTTPS"); return 1; }
        listen(tls_sock, 4096);
        struct epoll_event tev = { .events = EPOLLIN, .data.fd = tls_sock };
        epoll_ctl(epfd, EPOLL_CTL_ADD, tls_sock, &tev);
        printf(", HTTPS on :%d", tls_port);
    }
    printf(" (epoll, keep-alive, cached)\n");
    fflush(stdout);

    /* Main loop */
    struct epoll_event events[MAX_EVENTS];
    while (running) {
        int n = epoll_wait(epfd, events, MAX_EVENTS, 1000);
        for (int i = 0; i < n; i++) {
            int fd = events[i].data.fd;
            if (fd == sock) do_accept(sock, 0);
            else if (fd == tls_sock) do_accept(tls_sock, 1);
            else do_read(fd);
        }
    }

    printf("\n%ld requests served, %ld bytes, cache %ld/%ld (%.1f%% hit rate)\n",
           total_requests, total_bytes, cache_hits, cache_hits + cache_misses,
           (cache_hits+cache_misses) > 0 ? 100.0*cache_hits/(cache_hits+cache_misses) : 0.0);

    close(sock);
    if (tls_sock >= 0) close(tls_sock);
    if (tls_ctx) u_tls_ctx_free(tls_ctx);
    close(epfd);
    return 0;
}
